Chapter 7<br/>
< Linear Regression w/sklearn >
===============================

In [1]:
from sklearn.datasets import load_boston
import matplotlib.pyplot as plt
import numpy as np

In [2]:
boston = load_boston()

In [3]:
x_data = boston.data
y_data = boston.target.reshape(boston.target.size, 1)

x_data[:3]

array([[  6.32000000e-03,   1.80000000e+01,   2.31000000e+00,
          0.00000000e+00,   5.38000000e-01,   6.57500000e+00,
          6.52000000e+01,   4.09000000e+00,   1.00000000e+00,
          2.96000000e+02,   1.53000000e+01,   3.96900000e+02,
          4.98000000e+00],
       [  2.73100000e-02,   0.00000000e+00,   7.07000000e+00,
          0.00000000e+00,   4.69000000e-01,   6.42100000e+00,
          7.89000000e+01,   4.96710000e+00,   2.00000000e+00,
          2.42000000e+02,   1.78000000e+01,   3.96900000e+02,
          9.14000000e+00],
       [  2.72900000e-02,   0.00000000e+00,   7.07000000e+00,
          0.00000000e+00,   4.69000000e-01,   7.18500000e+00,
          6.11000000e+01,   4.96710000e+00,   2.00000000e+00,
          2.42000000e+02,   1.78000000e+01,   3.92830000e+02,
          4.03000000e+00]])

In [4]:
from sklearn import preprocessing

minmax_scale = preprocessing.MinMaxScaler().fit(x_data)
x_scaled_data = minmax_scale.transform(x_data)

x_scaled_data[:3]

array([[  0.00000000e+00,   1.80000000e-01,   6.78152493e-02,
          0.00000000e+00,   3.14814815e-01,   5.77505269e-01,
          6.41606591e-01,   2.69203139e-01,   0.00000000e+00,
          2.08015267e-01,   2.87234043e-01,   1.00000000e+00,
          8.96799117e-02],
       [  2.35922539e-04,   0.00000000e+00,   2.42302053e-01,
          0.00000000e+00,   1.72839506e-01,   5.47997701e-01,
          7.82698249e-01,   3.48961980e-01,   4.34782609e-02,
          1.04961832e-01,   5.53191489e-01,   1.00000000e+00,
          2.04470199e-01],
       [  2.35697744e-04,   0.00000000e+00,   2.42302053e-01,
          0.00000000e+00,   1.72839506e-01,   6.94385898e-01,
          5.99382080e-01,   3.48961980e-01,   4.34782609e-02,
          1.04961832e-01,   5.53191489e-01,   9.89737254e-01,
          6.34657837e-02]])

In [5]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(x_scaled_data,
                                                    y_data,
                                                    test_size = 0.2)

In [6]:
from sklearn import  linear_model

regr = linear_model.LinearRegression(fit_intercept = True, 
                                     normalize = False, 
                                     copy_X = True, 
                                     n_jobs = 8)
regr.fit(X_train, y_train)
regr

/anaconda3/lib/python3.6/site-packages/scipy/linalg/basic.py:1018: RuntimeWarning: internal gelsd driver lwork query error, required iwork dimension not returned. This is likely the result of LAPACK bug 0038, fixed in LAPACK 3.2.2 (released July 21, 2010). Falling back to 'gelss' driver.
  warnings.warn(mesg, RuntimeWarning)


LinearRegression(copy_X=True, fit_intercept=True, n_jobs=8, normalize=False)

In [7]:
y_true = y_test
y_pred = regr.predict(X_test)

In [8]:
np.sqrt(((y_true - y_pred) ** 2).sum() / len(y_true))

5.4056605465134853

In [9]:
from sklearn.metrics import mean_squared_error

np.sqrt(mean_squared_error(y_true, y_pred))

5.4056605465134853

In [10]:
print('Coefficients: ', regr.coef_)
print('intercept: ', regr.intercept_)

Coefficients:  [[ -8.24950323   5.00296377   1.08366228   1.93168854  -7.38912577
   22.17347817  -0.94623836 -14.90688722   6.21781777  -6.22619742
   -8.47839934   3.77995887 -16.81581969]]
intercept:  [ 24.22734951]


In [11]:
regr.predict(x_data[:5])

array([[-414.05005437],
       [-276.77881919],
       [-172.45066805],
       [ -35.45955325],
       [ -72.01600143]])

In [12]:
x_data[:5].dot(regr.coef_.T) + regr.intercept_

array([[-414.05005437],
       [-276.77881919],
       [-172.45066805],
       [ -35.45955325],
       [ -72.01600143]])

In [13]:
from sklearn.metrics import r2_score
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error

In [14]:
y_true = y_test
y_hat = regr.predict(X_test)

r2_score(y_true, y_hat), mean_absolute_error(y_true, y_hat), mean_squared_error(y_true, y_hat)

(0.70205532836315498, 3.5286008400170092, 29.221165944132473)

In [15]:
y_true = y_train
y_hat = regr.predict(X_train)

r2_score(y_true, y_hat), mean_absolute_error(y_true, y_hat), mean_squared_error(y_true, y_hat)

(0.74892255900766469, 3.1387612816387578, 20.317302760097824)