Chapter 10<br/>
< Classification Service >
===============================

In [1]:
import pandas as pd
import numpy as np

In [2]:
data_source = "https://stats.idre.ucla.edu/stat/data/binary.csv"
df = pd.read_csv(data_source)

df[:5]

admit  gre   gpa  rank
0      0  380  3.61     3
1      1  660  3.67     3
2      1  800  4.00     1
3      1  640  3.19     4
4      0  520  2.93     4

In [3]:
y_data = df['admit'].values.reshape(-1, 1)
x_data = df.ix[:,1:].values

y_data[:5], x_data[:5]

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate_ix
  


(array([[0],
        [1],
        [1],
        [1],
        [0]]), array([[ 380.  ,    3.61,    3.  ],
        [ 660.  ,    3.67,    3.  ],
        [ 800.  ,    4.  ,    1.  ],
        [ 640.  ,    3.19,    4.  ],
        [ 520.  ,    2.93,    4.  ]]))

In [4]:
from sklearn import preprocessing

min_max_scaler = preprocessing.MinMaxScaler()
x_data = min_max_scaler.fit_transform(x_data)

x_data[:5]

array([[ 0.27586207,  0.77586207,  0.66666667],
       [ 0.75862069,  0.81034483,  0.66666667],
       [ 1.        ,  1.        ,  0.        ],
       [ 0.72413793,  0.53448276,  1.        ],
       [ 0.51724138,  0.38505747,  1.        ]])

In [5]:
from sklearn import linear_model, datasets

logreg = linear_model.LogisticRegression(fit_intercept=True)
logreg.fit(x_data, y_data.ravel())

sum(logreg.predict(x_data) == y_data.ravel()) / len(y_data.ravel())

0.70750000000000002

In [6]:
theta = np.append(logreg.intercept_, logreg.coef_.ravel())
theta

array([-1.25437362,  0.89883582,  0.97923028, -1.54994771])

In [7]:
theta_file_name = "theta_bin.npy"
np.save(theta_file_name, theta)

In [8]:
np.load(theta_file_name)

array([-1.25437362,  0.89883582,  0.97923028, -1.54994771])

In [9]:
min_max = np.vstack((df.ix[:,1:].values.min(axis=0),
                     df.ix[:,1:].values.max(axis=0)))
min_max

array([[ 220.  ,    2.26,    1.  ],
       [ 800.  ,    4.  ,    4.  ]])

In [10]:
min_max_file_name = "min_max.npy"
np.save(min_max_file_name, min_max)

In [11]:
np.load(min_max_file_name)

array([[ 220.  ,    2.26,    1.  ],
       [ 800.  ,    4.  ,    4.  ]])

In [12]:
np.load(theta_file_name)

array([-1.25437362,  0.89883582,  0.97923028, -1.54994771])

In [13]:
import pickle

f = open('logicmodel.pkl', 'wb')
f.seek(0)

pickle.dump(logreg, f)
f.close()

In [14]:
fr = open('./logicmodel.pkl', 'rb')
logreg_pickle = pickle.load(fr)

sum(logreg.predict(x_data) == logreg_pickle.predict(x_data)) / len(y_data.ravel())

1.0