Chapter 5<br/>
< Numerical Python - Numpy >
===============================


### 코드로 방정식 표현하기
- 2x₁ + 2x₂ + x₃ = 9<br/>
2x₁ - x₂ + 2x₃ = 6<br/>
x₁ - x₂ + 2x₃ = 5
- [2 2 1 9]<br/>
[2 -1 2 5]<br/>
[1 -1 2 5]

```python
coefficient_matrix = [[2, 2, 1], [2, -1, 2], [1, -1, 2]]
constant_vector = [9, 6, 5]
```

- 다양한 Matrix 계산을 어떻게 만들 것인가?
- 굉장히 큰 Matrix에 대한 표현
- 처리 속도 문제 -> 파이썬은 Interpreter 언어
> 적절한 패키지를 활용하는 것은 좋은 방법


### 파이썬 과학 처리 패키지 : Numpy
- Numerical Python
- 파이썬의 고성능 과학 계산용 패키지
- Matrix와 Vector와 같은 Array연산의 사실상 표준
- 한굴로 넘파이로 주로 통칭



### Numpy 특징
- 일반 `List`에 비해 빠르고, 메모리 효율적
- 반복문 없이 데이터 배열에 대한 처리 지원
- 선형대수와 관련된 다양한 기능 제공
- C, C++, 포트란 등의 언어와 통합 가능


### import

In [1]:
import numpy as np

- `numpy`의 호출 방법
- 일반적으로 `numpy는 `np`라는 별칭을 이용해서 호출
- 특별한 이유는 없다.

### Array creation

In [2]:
test_array = np.array([1, 4, 5, 8], float)
print(test_array)
print(type(test_array[3]))

[ 1.  4.  5.  8.]
<class 'numpy.float64'>


- `numpy`는 `np.array()`함수를 활용하여 배열을 생성 -> ndarray
- `numpy`는 하나의 데이터 타입만 배열에 넣을 수 있다.
- `List`와 가장 큰 차이점, Dynamic typing not supported
- C의 Array를 사용하여 배열을 생성

In [3]:
print(test_array.dtype)
print(test_array.shape)

float64
(4,)


- shape : numpy array의 objectdml dimension 구성을 반환
- dtype : numpy array의 데이터 type을 반환


### Array shape (vector)
- Array(vector, matrix, tensor)의 크기, 형태 등에 대한 정보

In [4]:
test_array = np.array([1, 4, 5, '8'], float)
print(test_array)
print(test_array.shape)

[ 1.  4.  5.  8.]
(4,)


### Array shape (matrix)

In [5]:
matrix = [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]]
print(np.array(matrix, int).shape)

(3, 4)


### Array shape (3rd order tensor)

In [6]:
tensor = [[[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
          [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
          [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
          [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]]]
print(np.array(tensor, int).shape)

(4, 3, 4)


### Array shape (ndim & size)
- ndim : number of dimension
- size : data의 개수

In [7]:
tensor = [[[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
          [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
          [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
          [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]]]

In [8]:
print(np.array(tensor, int).ndim)

3


In [9]:
print(np.array(tensor, int).size)

48


### Array dtype
- Ndarray의 single element가 가지는 data type
- 각 element가 차지하는 memory의 크기가 결정
- C의 data type과 compatible

In [10]:
np.array([[1, 2, 3], [4.5, 5, 6]], dtype = int)

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
np.array([[1, 2, 3], [4.5, '5', '6']], dtype = np.float32)

array([[ 1. ,  2. ,  3. ],
       [ 4.5,  5. ,  6. ]], dtype=float32)

- nbytes : ndarray object의 메모리 크기를 반환

In [12]:
np.array([[1, 2, 3], [4.5, '5', '6']], dtype = np.float32).nbytes

24

In [13]:
np.array([[1, 2, 3], [4.5, '5', '6']], dtype = np.int8).nbytes

6

In [14]:
np.array([[1, 2, 3], [4.5, '5', '6']], dtype = np.float64).nbytes

48

### reshape
- Array의 shape의 크기를 변경(element의 갯수는 동일)
- Array의 size만 같다면 다차원으로 자유로이 변형 가능

In [15]:
test_matrix = [[1, 2, 3, 4], [1, 2, 5, 8]]
np.array(test_matrix).shape

(2, 4)

In [16]:
np.array(test_matrix).reshape(8,).shape

(8,)

In [17]:
np.array(test_matrix).reshape(2, 4).shape

(2, 4)

- -1 : size를 기반으로 row 개수 선정

In [18]:
np.array(test_matrix).reshape(-1, 2).shape

(4, 2)

In [19]:
np.array(test_matrix).reshape(2, 2, 2)

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [5, 8]]])

In [20]:
np.array(test_matrix).reshape(2, 2, 2).shape

(2, 2, 2)

### flatten
- 다차원 array를 1차원 array로 변환

In [21]:
test_matrix = [[[1, 2, 3, 4], [1, 2, 5, 8]], [[1, 2, 3, 4], [1, 2, 5, 8]]]
np.array(test_matrix).flatten()

array([1, 2, 3, 4, 1, 2, 5, 8, 1, 2, 3, 4, 1, 2, 5, 8])

### indexing
- `List`와 달리 이차원 배열에서 [0, 0]과 같은 표기법 제공
- Matrix일 경우 앞은 row 뒤는 column을 의미

In [22]:
a = np.array([[1, 2, 3], [4.5, 5, 6]], int)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
print(a[0, 0])
print(a[0][0])

1
1


In [24]:
a[0, 0] = 12
a

array([[12,  2,  3],
       [ 4,  5,  6]])

In [25]:
a[0][0] = 5
a

array([[5, 2, 3],
       [4, 5, 6]])

### slicing
- `List`와 달리 행과 열 부분을 나눠서 slicing 가능
- Matrix의 부분 집합을 추출할 때 사용

In [26]:
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], int)
a[:2:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [27]:
a[1,1:3]

array([7, 8])

In [28]:
a[1:3]

array([[ 6,  7,  8,  9, 10]])

In [29]:
test_example = np.array([[1, 2, 5, 8],
                         [1, 2, 5, 8],
                         [1, 2, 5, 8],
                         [1, 2, 5, 8],], int)
test_example[:2:]

array([[1, 2, 5, 8],
       [1, 2, 5, 8]])

In [30]:
test_example[:, 1:3]

array([[2, 5],
       [2, 5],
       [2, 5],
       [2, 5]])

In [31]:
test_example[1, :2]

array([1, 2])

In [32]:
test_example[:, ::2]

array([[1, 5],
       [1, 5],
       [1, 5],
       [1, 5]])

In [33]:
test_example[::2, ::3]

array([[1, 8],
       [1, 8]])

### arange

- array의 범위를 지정하여 값의 `List`를 생성하는 명령어

In [34]:
np.arange(30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [35]:
np.arange(0, 5, 0.5)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [36]:
np.arange(30).reshape(5, 6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

### ones, zeros and empty
- zeros : 0 으로 가득찬 ndarry 생성

In [37]:
np.zeros(shape = (10,), dtype = np.int8)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [38]:
np.zeros((2, 5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

- ones : 1로 가득찬 ndarray 생성

In [39]:
np.ones(shape = (10,), dtype = np.int8)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [40]:
np.ones((2, 5))

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

- empty : shape만 주어지고 비어있는 ndarray 생성

In [41]:
np.empty(shape = (10,), dtype = np.int8)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [42]:
np.empty((3, 5))

array([[ -1.72723371e-077,  -1.72723371e-077,   4.94065646e-323,
          0.00000000e+000,   0.00000000e+000],
       [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
          0.00000000e+000,   0.00000000e+000],
       [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
                      nan,  -1.72723371e-077]])

### something_like
- 기존 ndarray의 shape 크기 만큼 1,0 또는 empty array를 반환

In [43]:
test_matrix = np.arange(30).reshape(5, 6)
np.ones_like(test_matrix)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

### identity
- 단위 행렬(i 행렬)을 생성
- n : number of rows

In [44]:
np.identity(n = 3, dtype = np.int8)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [45]:
np.identity(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

### eye
- 대각선이 1인 행렬, k값의 시작 index의 변경 가능

In [46]:
np.eye(N = 3, M = 5, dtype = np.int8)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]], dtype=int8)

In [47]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [48]:
np.eye(3, 5, k = 2)

array([[ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

### diag
- 대각 행렬의 값을 추출
- k : start index

In [49]:
matrix = np.arange(9).reshape(3, 3)
np.diag(matrix)

array([0, 4, 8])

In [50]:
np.diag(matrix, k = 1)

array([1, 5])

### random sampling
- 데이터 분포에 따른 sampling으로 array를 생성

In [51]:
np.random.uniform(0, 1, 10).reshape(2, 5) # 균등분포

array([[ 0.16436765,  0.27956321,  0.70281744,  0.0096368 ,  0.8493396 ],
       [ 0.69309358,  0.61292054,  0.53365725,  0.67474591,  0.65755798]])

In [52]:
np.random.normal(0, 1, 10).reshape(2, 5) # 정규분포

array([[ 1.27077398, -1.98354255, -1.72799392, -0.67776398,  0.00971298],
       [-1.50431842, -0.29218047, -1.22770996, -1.30932886, -0.0431671 ]])

### sum
- ndarray의 element들 간의 합을 계산
- list의 sum기능과 동일

In [53]:
test_array = np.arange(1, 11)
test_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [54]:
test_array.sum(dtype = np.float)

55.0

### axis
- 모든 operation function을 실행할 때, 기준이 되는 dimension 축

In [55]:
test_array = np.arange(1, 13).reshape(3, 4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [56]:
test_array.sum(axis = 1), test_array.sum(axis = 0)

(array([10, 26, 42]), array([15, 18, 21, 24]))

In [57]:
third_order_tensor = np.array([test_array, test_array, test_array])
third_order_tensor

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [58]:
third_order_tensor.sum(axis = 2)

array([[10, 26, 42],
       [10, 26, 42],
       [10, 26, 42]])

In [59]:
third_order_tensor.sum(axis = 1)

array([[15, 18, 21, 24],
       [15, 18, 21, 24],
       [15, 18, 21, 24]])

In [60]:
third_order_tensor.sum(axis = 0)

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36]])

### mean & std
- ndarray의 element들 간의 평균 또는 표준 편차를 반환

In [61]:
test_array = np.arange(1, 13).reshape(3, 4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [62]:
test_array.mean(), test_array.mean(axis = 0)

(6.5, array([ 5.,  6.,  7.,  8.]))

In [63]:
test_array.std(), test_array.std(axis = 0)

(3.4520525295346629,
 array([ 3.26598632,  3.26598632,  3.26598632,  3.26598632]))

### Mathematical functions
- 그 외에도 다양한 수학 연산자 제공
- exponential
> `exp`, `expm1`, `exp2`, `log`, `log10`<br/>
> `loglp`, `log2`, `power`, `sqrt`

- trigonometric
> `sin`, `cos`, `tan`<br/>
> `acsin`, `arccos`, `atctan`

- hyperbolic
> `sinh`, `cosh`, `tanh`<br/>
> `acsinh`, `arccosh`, `atctanh`

### concatenate
- Numpy array를 합치는 함수

In [64]:
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
np.vstack((a, b))

array([[1, 2, 3],
       [2, 3, 4]])

In [65]:
a = np.array([[1], [2], [3]])
b = np.array([[2], [3], [4]])
np.hstack((a,b))

array([[1, 2],
       [2, 3],
       [3, 4]])

In [66]:
a = np.array([[1, 2, 3]])
b = np.array([[2, 3, 4]])
np.concatenate((a, b), axis = 0)

array([[1, 2, 3],
       [2, 3, 4]])

In [67]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b.T), axis = 1)

array([[1, 2, 5],
       [3, 4, 6]])

### Operations b/t arrays
- Numpy는 array간의 기본적인 사칙 연산 지원

In [68]:
test_a = np.array([[1, 2, 3], [4, 5, 6]], float)

In [69]:
test_a + test_a

array([[  2.,   4.,   6.],
       [  8.,  10.,  12.]])

In [70]:
test_a - test_a

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [71]:
test_a * test_a

array([[  1.,   4.,   9.],
       [ 16.,  25.,  36.]])

### Element-wise operations
- Array간 shape이 같을 때 일어나는 연산

In [72]:
matrix_a = np.arange(1, 13).reshape(3, 4)
matrix_a * matrix_a

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

### Dot product
- Matrix의 기본 연산
- dot 함수 사용

In [73]:
test_a = np.arange(1, 7).reshape(2, 3)
test_b = np.arange(7, 13).reshape(3, 2)

In [74]:
test_a.dot(test_b)

array([[ 58,  64],
       [139, 154]])

### Transpose
- transpose 또는 T attribute 사용

In [75]:
test_a = np.arange(1, 7).reshape(2, 3)
test_a

array([[1, 2, 3],
       [4, 5, 6]])

In [76]:
test_a.T.dot(test_a)

array([[17, 22, 27],
       [22, 29, 36],
       [27, 36, 45]])

In [77]:
test_a.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [78]:
test_a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

### broadcasting
- shape이 다른 배열 간 연산을 지원하는 기능

In [79]:
test_matrix = np.array([[1, 2, 3], [4, 5, 6]], float)
scalar = 3

In [80]:
test_matrix + scalar

array([[ 4.,  5.,  6.],
       [ 7.,  8.,  9.]])

In [81]:
test_matrix - scalar

array([[-2., -1.,  0.],
       [ 1.,  2.,  3.]])

In [82]:
test_matrix * 5

array([[  5.,  10.,  15.],
       [ 20.,  25.,  30.]])

In [83]:
test_matrix / 5

array([[ 0.2,  0.4,  0.6],
       [ 0.8,  1. ,  1.2]])

In [84]:
test_matrix // 0.2

array([[  4.,   9.,  14.],
       [ 19.,  24.,  29.]])

In [85]:
test_matrix ** 2

array([[  1.,   4.,   9.],
       [ 16.,  25.,  36.]])

- Scalar - Vector 외에도 Vector - Matrix 간의 연산도 지원

In [86]:
test_matrix = np.arange(1, 13).reshape(4, 3)
test_vector = np.arange(10, 40, 10)
test_matrix + test_vector

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39],
       [20, 31, 42]])

### Numpy performance
- timeit : jupyter 환경에서 코드의 퍼포먼스를 체크하는 함수
- 일반적인 속도 : for loop < list comprehension < numpy
- 1억번의 loop가 돌 때 약 4배 이상의 성능 차이를 보인다.
- Concatenate처럼 계산이 아닌, 할당에서는 연산 속도의 이점이 없다.

### All & Any
- Array의 데이터 전부(and) 또는 일부(or)가 조건 만족 여부 반환

In [87]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [88]:
np.any(a > 5), np.any(a < 0)

(True, False)

In [89]:
np.all(a > 5), np.all(a < 10)

(False, True)

### Comparison operation
- Numpy는 배열의 크기가 동일할 때 element간의 비교결과를<br/>
Boolean type으로 반환

In [90]:
test_a = np.array([1, 3, 0], float)
test_b = np.array([5, 2, 1], float)
test_a > test_b

array([False,  True, False], dtype=bool)

In [91]:
test_a == test_b

array([False, False, False], dtype=bool)

In [92]:
(test_a > test_b).any()

True

In [93]:
a = np.array([1, 3, 0], float)
np.logical_and(a > 0, a < 3)

array([ True, False, False], dtype=bool)

In [94]:
b = np.array([True, False, True], bool)
np.logical_not(b)

array([False,  True, False], dtype=bool)

In [95]:
c = np.array([False, True, False], bool)
np.logical_or(b, c)

array([ True,  True,  True], dtype=bool)

### np.where

In [96]:
np.where(a > 0, 3, 2)

array([3, 3, 2])

- index값 반환

In [97]:
a = np.arange(10)
np.where(a > 5)

(array([6, 7, 8, 9]),)

- Not a Number

In [98]:
a = np.array([1, np.NaN, np.Inf], float)
np.isnan(a)

array([False,  True, False], dtype=bool)

- is finite number

In [99]:
np.isfinite(a)

array([ True, False, False], dtype=bool)

### argmax & argmin
- array내 최댓값 또는 최솟값의 index 반환

In [100]:
a = np.array([1, 2, 4, 5, 8, 78, 23, 3])
np.argmax(a), np.argmin(a)

(5, 0)

- axis 기반의 반환

In [101]:
a = np.array([[1, 2, 4, 7], [9, 88, 6, 45], [9, 76, 3, 4]])
np.argmax(a, axis = 1), np.argmin(a, axis = 0)

(array([3, 1, 1]), array([0, 0, 2, 2]))

### boolean index
- numpy의 배열은 특정 조건에 따른 값을 배열 형태로 추출 가능
- Comparison operation 함수 모두 사용가능

In [102]:
test_array = np.array([1, 4, 0, 2, 3, 8, 9, 7], float)
test_array > 3

array([False,  True, False, False, False,  True,  True,  True], dtype=bool)

In [103]:
test_array[test_array > 3]

array([ 4.,  8.,  9.,  7.])

In [104]:
condition = test_array < 3
test_array[condition]

array([ 1.,  0.,  2.])

In [105]:
A = np.array([[12, 13, 14, 12, 16, 14, 11, 10,  9],
              [11, 14, 12, 15, 15, 16, 10, 12, 11],
              [10, 12, 12, 15, 14, 16, 10, 12, 12],
              [ 9, 11, 16, 15, 14, 16, 15, 12, 10]])
B = A < 15
B.astype(np.int)

array([[1, 1, 1, 1, 0, 1, 1, 1, 1],
       [1, 1, 1, 0, 0, 0, 1, 1, 1],
       [1, 1, 1, 0, 1, 0, 1, 1, 1],
       [1, 1, 0, 0, 1, 0, 0, 1, 1]])

### fancy index
- numpy의 array를 index value로 사용해서 값을 추출하는 방법

In [106]:
a = np.array([2, 4, 6, 8], float)
b = np.array([0, 0, 1, 3, 2, 1], int)
a[b]

array([ 2.,  2.,  4.,  8.,  6.,  4.])

In [107]:
a.take(b)

array([ 2.,  2.,  4.,  8.,  6.,  4.])

- Matrix형태의 데이터도 가능

In [108]:
a = np.array([[1, 4], [9, 16]], float)
b = np.array([0, 0, 1, 1, 0], int)
c = np.array([0, 1, 1, 1, 1], int)
a[b, c]

array([  1.,   4.,  16.,  16.,   4.])

### loadtxt & savetxt
- Text type의 데이터를 읽고 저장하는 기능

In [109]:
a = np.loadtxt('./populations.txt')
a[:10]

array([[  1900.,  30000.,   4000.,  48300.],
       [  1901.,  47200.,   6100.,  48200.],
       [  1902.,  70200.,   9800.,  41500.],
       [  1903.,  77400.,  35200.,  38200.],
       [  1904.,  36300.,  59400.,  40600.],
       [  1905.,  20600.,  41700.,  39800.],
       [  1906.,  18100.,  19000.,  38600.],
       [  1907.,  21400.,  13000.,  42300.],
       [  1908.,  22000.,   8300.,  44500.],
       [  1909.,  25400.,   9100.,  42100.]])

In [110]:
a_int = a.astype(int)
a_int[:3]

array([[ 1900, 30000,  4000, 48300],
       [ 1901, 47200,  6100, 48200],
       [ 1902, 70200,  9800, 41500]])

In [111]:
np.savetxt('int_data.csv', a_int, delimiter = ',')

### numpy object - npy
- Numpy object (pickle) 형태로 데이터를 저장하고 불러옴
- Binary 파일 형태로 저장

In [112]:
np.save('npy_test', arr = a_int)

In [113]:
npy_array = np.load(file = 'npy_test.npy')
npy_array[:3]

array([[ 1900, 30000,  4000, 48300],
       [ 1901, 47200,  6100, 48200],
       [ 1902, 70200,  9800, 41500]])