Chapter 5<br/>
< Numerical Python - Numpy >
===============================


### 코드로 방정식 표현하기
- 2x₁ + 2x₂ + x₃ = 9<br/>
2x₁ - x₂ + 2x₃ = 6<br/>
x₁ - x₂ + 2x₃ = 5
- [2 2 1 9]<br/>
[2 -1 2 5]<br/>
[1 -1 2 5]

```
coefficient_matrix = [[2, 2, 1], [2, -1, 2], [1, -1, 2]]
constant_vector = [9, 6, 5]
```

- 다양한 Matrix 계산을 어떻게 만들 것인가?
- 굉장히 큰 Matrix에 대한 표현
- 처리 속도 문제 -> 파이썬은 Interpreter 언어
> 적절한 패키지를 활용하는 것은 좋은 방법


### 파이썬 과학 처리 패키지 : Numpy
- Numerical Python
- 파이썬의 고성능 과학 계산용 패키지
- Matrix와 Vector와 같은 Array연산의 사실상 표준
- 한굴로 넘파이로 주로 통칭



### Numpy 특징
- 일반 `List`에 비해 빠르고, 메모리 효율적
- 반복문 없이 데이터 배열에 대한 처리 지원
- 선형대수와 관련된 다양한 기능 제공
- C, C++, 포트란 등의 언어와 통합 가능


### import

In [1]:
import numpy as np

- `numpy`의 호출 방법
- 일반적으로 `numpy는 `np`라는 별칭을 이용해서 호출
- 특별한 이유는 없다.

### Array Creation

In [2]:
test_array = np.array([1, 4, 5, 8], float)
print(test_array)
type(test_array[3])

[ 1.  4.  5.  8.]


numpy.float64

- `numpy`는 `np.array()`함수를 활용하여 배열을 생성 -> ndarray
- `numpy`는 하나의 데이터 타입만 배열에 넣을 수 있다.
- `List`와 가장 큰 차이점, Dynamic typing not supported
- C의 Array를 사용하여 배열을 생성